import { formatDate } from "../../../components/admin/utils/date";

export const newApplicantsData = [
    {
        id: "00001",
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("4/7/2019"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00002",
        name: "Jane Smith",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("5/8/2023"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00003",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00004",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00005",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00006",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00007",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00008",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00009",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00010",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00011",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Reissue",
        status: "Processing",
    },
    {
        id: "00012",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Completed",
    },
    {
        id: "00001",
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "4/7/2019",
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00002",
        name: "Jane Smith",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "5/8/2023",
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00003",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00004",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00005",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00006",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00007",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00008",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00009",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00010",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00011",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Reissue",
        status: "Processing",
    },
    {
        id: "00012",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Completed",
    },
    {
        id: "00001",
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "4/7/2019",
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00002",
        name: "Jane Smith",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "5/8/2023",
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00003",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00004",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00005",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00006",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00007",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00008",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00009",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00010",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00011",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Reissue",
        status: "Processing",
    },
    {
        id: "00012",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Completed",
    },
    {
        id: "00001",
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "4/7/2019",
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00002",
        name: "Jane Smith",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "5/8/2023",
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00003",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00004",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00005",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00006",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00007",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00008",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00009",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00010",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00011",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Reissue",
        status: "Processing",
    },
    {
        id: "00012",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Completed",
    },
    {
        id: "00001",
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "4/7/2019",
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00002",
        name: "Jane Smith",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: "5/8/2023",
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00003",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00004",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00005",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00006",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00007",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00008",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Processing",
    },
    {
        id: "00009",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Completed",
    },
    {
        id: "00010",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "New Application",
        status: "Rejected",
    },
    {
        id: "00011",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Reissue",
        status: "Processing",
    },
    {
        id: "00012",
        name: "Alice Johnson",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Completed",
    },
];

export const newApplicantsColumns = [
    { id: "id", header: "ID" },
    { id: "name", header: "Name" },
    { id: "address", header: "Address" },
    { id: "dateApplied", header: "Date" },
    { id: "type", header: "Type" },
    { id: "status", header: "Status" },
];